name: Deploy to Yandex Cloud (DISABLED)

# Временно отключен из-за отсутствия SSH ключей
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    # Временно отключаем серверную часть
    # - name: Install server dependencies
    #   run: cd server && npm ci

    # - name: Build server
    #   run: cd server && npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 158.160.177.251
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/aero-lunch-app
          git pull origin main
          
          # Обновляем фронтенд
          npm ci
          npm run build
          
          # Обновляем бэкенд
          cd server
          npm ci
          npm run build
          
          # Перезапускаем сервер
          pm2 restart aero-lunch-backend
          
          echo "✅ Деплой завершён!" 