name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Install server dependencies
      run: cd server && npm ci

    - name: Build server
      run: cd server && npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/aero-lunch
          git pull origin main
          
          # Обновляем фронтенд
          npm ci
          npm run build
          
          # Обновляем бэкенд
          cd server
          npm ci
          npm run build
          
          # Перезапускаем сервисы
          cd ..
          docker-compose down
          docker-compose up -d --build
          
          echo "✅ Деплой завершён!" 